describe("template spec", () => {
  it("passes", () => {
    cy.visit("http://localhost:5173/");
    cy.get('input[id="vertical"]').eq(0).type("2");
    cy.get('input[id="horizontal"]').eq(0).type("2");
    cy.get('select[id="facing"]').select("WEST");
    cy.get("button").contains("Generate").eq(0).click();
    //
    cy.get('select[id="action"]').select("PLACE_WALL");
    cy.get('input[id="vertical"]').eq(0).clear().type("1");
    cy.get('input[id="horizontal"]').eq(0).clear().type("1");
    cy.get("button").contains("Generate").eq(0).click();
    //
    cy.get('input[id="vertical"]').eq(0).clear().type("2");
    cy.get('input[id="horizontal"]').eq(0).clear().type("2");
    cy.get("button").contains("Generate").eq(0).click();
    //
    cy.get('input[id="vertical"]').eq(0).clear().type("1");
    cy.get('input[id="horizontal"]').eq(0).clear().type("3");
    cy.get("button").contains("Generate").eq(0).click();
    //
    cy.get('select[id="action"]').select("LEFT");
    cy.get("button").contains("Generate").eq(0).click();
    cy.wait(1000);
    cy.get("button").contains("Generate").eq(0).click();
    //
    cy.get('select[id="action"]').select("MOVE");
    cy.get("button").contains("Generate").eq(0).click();
    //
    cy.get('select[id="action"]').select("REPORT");
    cy.get("button").contains("Generate").eq(0).click();
  });
});
